[
  {'./granum.png': 'P6OxKvWfGCwBFr94PVLpnYwZ2igr7oboM79AGGfR9F4'},
  {
    'Dead/Images/cypripediu-calceolus.png':
      '2ZdsLqwqlWIEp4qpSWGnKeAlmt4vZgMbvpQT74p0J6w',
  },
  {
    'Dead/Images/dendrophylax-lindenii.png':
      'KyCJ0iog8TGNYIXofWe2isRpMbQ1Uklrf39rfiWJd9w',
  },
  {
    'Dead/Images/guarianthe-aurantiaca.png':
      'bYo4xf76HvIUzV5DyH3Ycr0ENWDicOroGk0Dio1s15M',
  },
  {
    'Dead/Images/miltonia-kayasimae.png':
      'ccV6VpfGf8kw1K1YFJCsU1c6yq_tvQAC5zp9M19_pqA',
  },
  {
    'Dead/Images/paphiopedilum-rothschildianum.png':
      '0Ykl7_JQ4OYTdmewe_apaIqzOh7aDLuX5Xqkfo5DCdg',
  },
  {
    'Dead/Images/paphiopedilum-vietnamense.png':
      'caNeGMMIvhyt0fETstzBbdzQby6zGputd1M7sO7X0Uk',
  },
  {
    'Dead/Images/phalaenopsis-micholitzii.png':
      '1per50KPNZxVetjB9yKUe5sVbwh_WvT0MPVhJQB9RHc',
  },
  {
    'Dead/Images/platanthera-azorica.png':
      '5uYbTWFEsx9r_sxHPGrvvdKNhzIjvZStJhA_vdDlbcA',
  },
  {
    'Dead/Images/shenzhenica-orchidaceae.png':
      'DfJSn_KCFg5gC1iS3628O6TykyqX4PortNGQkeD1_3c',
  },
  {
    'Dead/Images/vanda-coerulea.png':
      'eSnqakNOfTyEjHIWkAJZiRmS6wCCwdx_fJ3l0EUJPXM',
  },
  {
    'Flowering/Images/blue-vanda.png':
      'QuviKlh5fUq03KKOPxu1k9HHddwrnC1Rll3jo13xuHw',
  },
  {
    'Flowering/Images/ghost-orchid.png':
      '4K8PR1BLhwV0IsBG1PwR49vuqQBFc7_ZBdZJTwDmQcw',
  },
  {
    'Flowering/Images/gold-of-kinabalu.png':
      'kteMx6ZoVTxw4g7KY7MqYnxOw_8zPGWKUYKkw3tHnzE',
  },
  {
    'Flowering/Images/hochstetter-butterfly.png':
      'MLLJWCVmwmQMpZKo7OtBFzmK6ww7Qh4KqauELMJw3RM',
  },
  {
    'Flowering/Images/lady-slipper.png':
      'eS-cwe_NVSaJCd6emWoatibng4CeL7oXumMLhfno_wA',
  },
  {
    'Flowering/Images/miltonia-kayasimae.png':
      '-JQ-7MuC-LmEIzmcw2aOCzMF7AKqwucI6WUAtZyuxt4',
  },
  {
    'Flowering/Images/orange-cattleya.png':
      'qCWdazZUh7IwwgBYcW83Ow269GGCsz3eoLozcurdYfw',
  },
  {
    'Flowering/Images/shenzen-nongke.png':
      'xNwURGyQAbuAGdRYJMrgny1dB2-2X6LRPw8BozXHRpU',
  },
  {
    'Flowering/Images/vietnamese-paphiopedilum.png':
      'b55GXyMDkT6ogbvHesqGcYYwlCEX2ybj2OXIkCoz6IU',
  },
  {
    'Flowering/Images/white-moth.png':
      'ugalwFZ-C6kE91D_LzfdyUAZfSjfjgv7P5AvriywC8w',
  },
];
