[
  {'./granum.json': 'pHm6ysVq154aZ171iU0izH68t_sjGMglQvqxYNDA4h0'},
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/cypripediu-calceolus.json':
      'cam_7pRCFsDszqTjih_toj6B_Xl9oY3Ndy-Egc5IEhI',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/dendrophylax-lindenii.json':
      'LSp4B5T3B0HFXRU6P1qR1bMo6cTCOCGrGOZRj5IW6R0',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/guarianthe-aurantiaca.json':
      '5qBF2IB8sCzmp4MNn2GG24OTfreHWx4ooVI6OYUqvBk',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/miltonia-kayasimae.json':
      'WUFIJOnggBM8JeXlOM_iKVLqIipavfZhic1zcC5GkMw',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/paphiopedilum-rothschildianum.json':
      '22JEnCLgN7qX1d-4VeXHRdXPl87P2zxENJxQFYC6J8k',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/paphiopedilum-vietnamense.json':
      'pHiPaw4T7PPnkO4yu2xYW7i-itQkYqVLZUUSvz9lE0w',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/phalaenopsis-micholitzii.json':
      'OPIRLIcORdTTuI-bWcQfShctfDjYv2nCtitzUGioDxg',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/platanthera-azorica.json':
      'gYJcHxh2l67m1xfuibbF8zzZ2J43dpOmT0ftVWStvns',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/shenzhenica-orchidaceae.json':
      'f1_jQ1fVLmRJ-JKMgIe3XqtTzJl-7rX1igYcQjFhpVA',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Dead/vanda-coerulea.json':
      'OQiKGwQSmZlZxcGccrtu1ov6f2FfPSmD1ZicBaUzNCc',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/cypripediu-calceolus.json':
      '62abDISfRV8yjSzk-xCm8TsYpjUZ91sCwQaBPvAxH8k',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/dendrophylax-lindenii.json':
      'cwZB7FOgWK052sHrGe-vE9Z7t1dmKe3DSSyDPtBMY0c',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/guarianthe-aurantiaca.json':
      'Yj42tKSh8M4MLirT1JmckDbDPzekMX7Vv6qp7Y93TAE',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/miltonia-kayasimae.json':
      'IILQaYkW3iYDw3OYSwLfbZFx_14jdIu3nUwMDYBBtuQ',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/paphiopedilum-rothschildianum.json':
      'oeGa3OqppFm1OONslz7xuValA2d4KCU0vKqnOTIyXdw',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/paphiopedilum-vietnamense.json':
      'NEc4qWJwKSkmLgglfi9PmLYxASlbpmDBa4e9SxJxWuU',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/phalaenopsis-micholitzii.json':
      'KBTtR60gLZMvp5DTDiVv08vecD96bh_V3W-8ko3QVQg',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/platanthera-azorica.json':
      'NO9h1G_V5M7jrhY4X18CpJi4stDJj4hQTv23qqHdSj8',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/shenzhenica-orchidaceae.json':
      'vxdAdCdwi2-Fn25UPRqzQPafS-g4H15wSe_7TbwW2s4',
  },
  {
    '/Users/samuelsbauch/Code/cryptorchids-contract/arweave/Flowering/vanda-coerulea.json':
      '0FhRkI4QhYcH_ROKdylSTGnrruOpwVlFZRZ5cBF6ikU',
  },
];
